name = "DataToolkitCore"
uuid = "caac3e55-418c-402e-a061-64d454aa8f4f"
authors = ["TEC <tec@tecosaur.com> and contributors"]
version = "0.10.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[weakdeps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"

[extensions]
AbstractTreesExt = "AbstractTrees"
MetaGraphsNextExt = "MetaGraphsNext"

[compat]
AbstractTrees = "0.2, 0.3, 0.4"
Compat = "3.29, 4"
MetaGraphsNext = "0.5, 0.6"
PrecompileTools = "1"
Preferences = "1.2"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
